name: Bookkeeper
description: Personal Finance App.
publish_to: 'none'
version: 0.0.2+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  sqflite: ^1.3.0
  intl: ^0.16.1
  path_provider: ^1.6.7
  flutter_masked_text: ^0.8.0
  shared_preferences: ^0.5.7
  loadmore: ^1.0.4
  flutter_svg: ^0.17.4
  flutter_speed_dial: ^1.2.5
  line_awesome_icons: ^1.0.4+2
  url_launcher: ^5.4.10
  grouped_list: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-Black.ttf
          weight: 900